gNI_ = cooling_rates[10, :]
gNIII_ = cooling_rates[11, :]
gNIV_ = cooling_rates[12, :]
gNV_ = cooling_rates[13, :]
gNVI_ = cooling_rates[14, :]
gNVII_ = cooling_rates[15, :]
gNVIII_ = cooling_rates[16, :]
