gOII_ = cooling_rates[17, :]
gOIII_ = cooling_rates[18, :]
gOIV_ = cooling_rates[19, :]
gOV_ = cooling_rates[20, :]
gOVI_ = cooling_rates[21, :]
gOVII_ = cooling_rates[22, :]
gOVIII_ = cooling_rates[23, :]
gOIX_ = cooling_rates[24, :]
