gOII = interp1d(Temp, gOII_, kind="linear", fill_value="extrapolate")
gOIII = interp1d(Temp, gOIII_, kind="linear", fill_value="extrapolate")
gOIV = interp1d(Temp, gOIV_, kind="linear", fill_value="extrapolate")
gOV = interp1d(Temp, gOV_, kind="linear", fill_value="extrapolate")
gOVI = interp1d(Temp, gOVI_, kind="linear", fill_value="extrapolate")
gOVII = interp1d(Temp, gOVII_, kind="linear", fill_value="extrapolate")
gOVIII = interp1d(Temp, gOVIII_, kind="linear", fill_value="extrapolate")
gOIX = interp1d(Temp, gOIX_, kind="linear", fill_value="extrapolate")
