gNI = interp1d(Temp, gNI_, kind="linear", fill_value="extrapolate")
gNIII = interp1d(Temp, gNIII_, kind="linear", fill_value="extrapolate")
gNIV = interp1d(Temp, gNIV_, kind="linear", fill_value="extrapolate")
gNV = interp1d(Temp, gNV_, kind="linear", fill_value="extrapolate")
gNVI = interp1d(Temp, gNVI_, kind="linear", fill_value="extrapolate")
gNVII = interp1d(Temp, gNVII_, kind="linear", fill_value="extrapolate")
gNVIII = interp1d(Temp, gNVIII_, kind="linear", fill_value="extrapolate")
