R_HII_to_HI_via_e_caseA_ = ratesAB[0, :] # H CaseA
R_HeII_to_HeI_via_e_caseA_ = ratesAB[1, :] # He CaseA
R_HI_to_HII_via_e_ = rates[111, :]
R_HI_to_Hm_via_e_ = rates[113, :]
R_Hm_to_HI_via_HI_ = rates[109, :]
R_Hm_to_HI_via_e_ = rates[110, :]
R_Hm_to_HI_via_HII_ = rates[112, :]
R_HeI_to_HeII_via_HII_ = rates[106, :]
R_HeI_to_HeII_via_e_ = rates[108, :]
R_HeII_to_HeIII_via_e_ = rates[0, :]
R_HeII_to_HeI_via_Hm_ = rates[103, :]
R_HeII_to_HeI_via_HI_ = rates[107, :]
R_HeIII_to_HeII_via_HI_ = rates[221, :]
R_HeIII_to_HeII_via_e_ = rates[222, :]
